os: osx
dist: trusty
language: node_js
node_js: v10
install:
    - npm i
script:
    - npm test
    - npm run build
deploy:
    provider: npm
    api_key:
        secure: "ubM19hBD3ZuN+VvjhJsPjuTZSt0tpZEtQeHWP+N/k2oM+y5/YytBy7QuVgnl3H7Q9aEueSlZdnYkBqqPzerBMdXbN9qEX0X8Z/UJTrL1Jc2n1djP83ijChSwitjMvzOP/QtEn6XQd2K5KxnliMmwC3/OTdymZHg7jiyVEtPGUAr4dFBEP1gVuFa+3JHU5L/CZOc6xiL5IXDJ5VpgnNcqFk4kZIufdiJj5iHLRQHWUFcCKX4EjNiZ1W+TdrBruu5SAoftF7Rg0f3zG8+7N2qwHezP9Y+HG1wALLmf2UWeG2atqD3ZMcw0eYdi7SaOKQQCPFEHExmOTY06O9fG/av7I3k48+M4ZsvGjYI99zqLKbsaGauVxT+V+3SVO96p9ChFzvLYtRz1ZIOpuK8nbLgNnE5Eq77iT61CfTrRtXpcmC/pc/SdoLEvYCcDlJIFipg1jDpxxC4PuYgX3cStwhHjBxybUZAiwRGAD0rkAV1VMKVNk4E6v9sIIo4E6TVA57F94iEHv4HbQArENWSMh47ShzaHJar62GrvqEWhq+bEQygDGD8eQ1GF+t/GE6N/zp8bA71bSaV0GKN6LcTbMLA7SkhlLC/sXWVkLANP6EEUSUcwTawI0JIy6Fo7b6wTA8QB8fWUQ47plhC8PoN+hBLhOlNXh53Cb/T9CrcqMEofFp0="
    email: smilingxinyi@gmail.com
    on:
        tags: true
        repo: "xuperchain/xuper-sdk-js"
        branch: master
