os: osx
dist: trusty
language: node_js
node_js: v10
install:
    - npm i
script:
    - npm test
    - npm run build
deploy:
    provider: npm
    email: smilingxinyi@gmail.com
    skip_cleanup: true
    api_key: "a18af458-7fd9-42d2-a5d1-c2dd93029f49"
    on:
        tags: true
        repo: "xuperchain/xuper-sdk-js"
        branch: master
