os: osx
dist: trusty
language: node_js
node_js: v10
install:
    - npm i
script:
    - npm run build
deploy:
    provider: npm
    api_key: bab647b5-704a-46d7-a4ba-5e3bce53a9d0
    email: smilingxinyi@gmail.com
    skip_cleanup: true
    on:
        tags: true
        repo: xuperchain/xuper-sdk-js
        branch: master
